### ISSUE TITLE
SES-006 => create handlers

### ISSUE THREAD

**Issue by matheusmelchiades** [matheusmelchiades/share-eat-server#6]
# TODO:

### PLACES
- [x] create test integrate to create all flow 
- [x] create route to get places 
    - PATH === '/place'
    - METHOD === 'GET'
- [x] create validations query to get places
- [x] create pagination to get places (if necessary)

 - [x] create handler to access model and get data 
     ** if has filter get data by filter

### PLACES
- [x] create test integrate to create all flow 
- [x] create route to get places 
    - PATH === '/plate/:placeId'
    - METHOD === 'GET'
- [x] create validations query to get places
- [x] create pagination to get places (if necessary)
- [x] create route to create a new plate
- [x] validate parameters of a new plate (payload, body or query)
- [x] create handler to acces model and get data by placeId
- [x] create handler to create a new plate of a plac

**Comment by matheusmelchiades** [comment]
Finalized all steps
